### ISSUE TITLE
Sanitize open redirect URLs

### ISSUE THREAD

**Issue by solbero** [solbero/social-insecurity#26]
We should sanitize open redirect URLs. Here is a code snippet on how to do it: [https://www.pythonkitchen.com/how-prevent-open-redirect-vulnerab-flask/](https://www.pythonkitchen.com/how-prevent-open-redirect-vulnerab-flask/)

**Comment by annejotun** [comment]
Fixed with PR#29

**Comment by annejotun** [comment]
Fixed with PR#29
